"""Initial migration

Revision ID: 567e623b8f5b
Revises:
Create Date: 2026-02-15 14:20:02.967996

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "567e623b8f5b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pizzas",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pizzas_name"), "pizzas", ["name"], unique=False)
    op.create_table(
        "toppings",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_toppings_name"), "toppings", ["name"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("reference", sa.String(length=6), nullable=False),
        sa.Column("pizza_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pizza_id"],
            ["pizzas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_reference"), "orders", ["reference"], unique=True)
    op.create_table(
        "order_toppings",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("topping_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topping_id"],
            ["toppings.id"],
        ),
        sa.PrimaryKeyConstraint("order_id", "topping_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_toppings")
    op.drop_index(op.f("ix_orders_reference"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_toppings_name"), table_name="toppings")
    op.drop_table("toppings")
    op.drop_index(op.f("ix_pizzas_name"), table_name="pizzas")
    op.drop_table("pizzas")
    # ### end Alembic commands ###
